import turtle

#Berserk Guts'ın Berserker işareti :D

drawing_board = turtle.Screen()
drawing_board.bgcolor("Red")

turtle_instance = turtle.Turtle()
turtle_instance.hideturtle()
turtle_instance.pensize(10)
turtle_instance.forward(100)
turtle_instance.left(90)
turtle_instance.forward(75)

vışş=turtle.Turtle()
vışş.hideturtle()
vışş.pensize(10)
vışş.left(90)
vışş.forward(100)
vışş.right(90)
vışş.forward(75)

turtleee=turtle.Turtle()
turtleee.hideturtle()
turtleee.pensize(10)
turtleee.back(100)
turtleee.left(90)
turtleee.back(100)
turtleee.left(90)
turtleee.back(100)
turtleee.left(90)
turtleee.back(100)
turtleee.left(90)
turtleee.back(100)

ahaha=turtle.Turtle()
ahaha.hideturtle()
ahaha.pensize(10)
ahaha.left(45)
ahaha.forward(143)

yuh=turtle.Turtle()
yuh.hideturtle()
yuh.pensize(10)
yuh.left(45)
yuh.forward(143)
yuh.left(35)
yuh.forward(20)

ana=turtle.Turtle()
ana.hideturtle()
ana.pensize(10)
ana.left(45)
ana.forward(143)
ana.forward(30)

pp=turtle.Turtle()
pp.hideturtle()
pp.pensize(10)
pp.left(45)
pp.forward(143)
pp.right(35)
pp.forward(25)

hhaa=turtle.Turtle()
hhaa.hideturtle()
hhaa.pensize(10)
hhaa.right(135)
hhaa.forward(143)

turtle.done()